assemble.c: don't use a case for get_broadcast_num()
Instead of using a case, use a conditional shift.

Signed-off-by: H. Peter Anvin <hpa@zytor.com>
(cherry picked from commit 2902fbc1d8d084f10bfee4d18a01b90266c6adae)

(Fixes Watcom build failure:
assemble.c(2161): Error! E1078: Invalid type for switch expression
assemble.c(2162): Error! W106: Constant out of range - truncated
 Watcom doesn't support 64-bit integers as switch values.
See: https://github.com/open-watcom/open-watcom-v2/issues/66 )