Fix rest of the build failures with Watcom:
Watcom doesn't support 64-bit integers as switch values.  See:
https://github.com/open-watcom/open-watcom-v2/issues/66

parser.c(224): Error! E1078: Invalid type for switch expression
parser.c(1046): Error! E1078: Invalid type for switch expression

Changed the offending switches into if..else as a work-around.
(Used #ifdef in parse_line() so the change is easily readable.)